# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ 'master', 'feature/test-ci' ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    - name: set up environment
      run: |
        mkdir -p ~/bin
        wget https://github.com/kubernetes-sigs/kind/releases/download/v0.8.1/kind-linux-amd64 -O ~/bin/kind
        wget https://github.com/mikefarah/yq/releases/download/3.2.1/yq_linux_amd64 -O ~/bin/yq
        wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz
        tar xvzf kustomize_v3.5.4_linux_amd64.tar.gz
        mv kustomize ~/bin/
        export PATH=${PATH}:~/bin
        which yq
        which kustomize
        which kind
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        pwd
        ls
        ./kubetest -h

